-- Generated by MIDI2LUA --
-- MIDI88: ON --
-- Short Notes: OFF --
-- Note Velocity: OFF --
-- Sustain Pedal: OFF --
-- Midi Spoofer: OFF --

bpm = 180

loadstring(game:HttpGet("https://cdn.jsdelivr.net/gh/hellohellohell012321/TALENTLESS@main/loader_main.lua", true))()

loadstring(game:HttpGet("https://gist.githack.com/talentless-custom-songs/ec42cfb1abff7de045f0d2786c5ca08e/raw/custom_song.lua", true))()
